# --------
# may 28 2025
# biztune.co.tz
#-----
server {

        listen 80;
        server_name biztune.co.tz biztune.mobiadafrica.co.tz;

        root /var/www/mobiad/vodacom-caller-tunes/public;
        index index.php;

        location / {
         try_files $uri $uri/ /index.php?$query_string;
         autoindex on;
        }

        location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        }
}

